[profile.default]
src = "src"
out = "out"
libs = ["lib", "dependencies"]
via_ir = false # false is cheaper but need this to lower the contract size
optimizer = true
optimizer_runs = 1500

evm_version = 'prague'
solc_version = '0.8.30'

isolate = true
extra_output = ["storageLayout"]
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[invariant]
runs = 1000
depth = 1000

[dependencies]
solady = "0.1.26"
eth-infinitism-account-abstraction = { version = "0.9.0", git = "https://github.com/eth-infinitism/account-abstraction.git", branch = "release-v09" }
"@openzeppelin-contracts" = "5.4.0"
a16z-halmos-cheatcodes = "6da4e692c357ba6d641a2e677a28298cac9f76ab"
forge-std = "1.11.0"


[lint]
exclude_lints = ["unwrapped-modifier-logic"]
