[profile.default]
src = "src"
out = "out"
libs = ["lib"]
via_ir = true
optimizer = true
run = 200
evm_version = 'prague'

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
